### ISSUE TITLE
Remove BCH from Bisq

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#61]
Those lunatics from the BCH camp are starting to sueing exchanges who listed BCH (Kraken) [1]. I think now the time has come to cut any connection with those scammers. BCH has created so much damage and their hash-war is probably the main reason for the current price crash in BTC. So that all sums up more then enough reason to not support anything related to BCH in any way. Ignoring them and removing them from all exchanges is IMO the best way to deal with it. Those who try to make their benefit by trading those coins help them to continue and cause more problems in the future. The cost they create are externalized to the whole crypto community by creating terribly bad reputation, confusion, price crashes and now law suites. Enough is enough. 

BCH is dead - they just don't know it yet.

If you support that proposal please add a thumbs up, otherwise a thumbs down. If we get a > 50% thumbs up voting we will remove BCH in the next release (the Faketoshi scamcoin we never added anyway). 

[1] http://www.unitedcorp.com/unitedcorp-launches-suit-against-bitmain-bitcoin-com-roger-ver-kraken-bitcoin-exchange-and-others-alleging-hijacking-of-the-bitcoin-cash-network/#

> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

**Comment by dm8885555** [comment]
BCH and the people involved in it have been immensely damaging.

**Comment by kezo777** [comment]
100% agree with Manfred. Remove the crap and ignore completely. BCH is bad , but Dr.Judas BSV is even worse. The beauty of Bitcoin consensus is,it works as a self cleaning mechanism. BCH fork last year was just that. Network got rid of few fuckwits and it's good for a long run. Now,how long it will take remains to be seen, but meanwhile let BCH and BSV fight with whoever they fighting and burn a holes in their pockets so deep,they will see their own dicks through it. This of course creates huge instability and all, but i can see some positive side to it. Obviously, the BTC price will fall even further, but it creates an incredibly nice oportunity for not so wealthy,who can see through smoke and mirrors, to actually own a piece of bitcoin without risking too much. Low cost should help adoption much better then high. But it will not be soon( it is more like pension fund in my opinion). 
Wish to thank BISQ team for extraordinary work in creating a trully decentralised  exchange platform and most importantly- a new and progresive bussiness model,when reward is based on now much work one contributes,not how rich one is.
Wish you all best of luck!!!

**Comment by meapistol** [comment]
Note that BCH will likely be 51% attacked also and exchanges are defenseless against this. All BTC-forks with the same POW are prone to this except BTC itself. All coins that use commodity chips for their POW, i. e. are ASIC-resistant, are also prone to 51% attacks (e. g. Vertcoin). I expect exchanges to delist all these coins in the near future.

**Comment by ManfredKarrer** [comment]
@meapistol Thanks for the info, not following much that crap. Another reason to remove it as it consumes effort for us to follow that stupid war they have. I am not interested to follow any wars between mafia gangs in other parts of the world as well. So why should I spend time on that?

**Comment by ManfredKarrer** [comment]
@kezo777 Thanks! You are welcome to contribute if you find any area where you can be active in Bisq. If you are a developer there is plenty of work ;-). But also if you are not, there are many areas....Best joiun our slack and get in touch there!

Like the "...burn a holes in their pockets so deep,they will see their own dicks through it" part ;-).

**Comment by JWWeatherman** [comment]
Absolutely BCH will be 51% attacked. However, since it is just a scam coin the dear leader will just issue a PoW change edict and it will continue as the fraud that it is (like all the other scam coins including monero). That said, I'm very happy it is starting someplace and BCH is a very obvious embarrassment.

**Comment by remyers** [comment]
Remove it and let Coinbase and other centralized exchanges deal with the legal risks and inevitable deep reorg mess.

**Comment by ManfredKarrer** [comment]
Yes would be fun to see a centralized exchange go bunkrupt by supporting those shitcoins. Probably too low volumes to be a real possibility...

**Comment by stachrom** [comment]
just remove it!

**Comment by clearwater-trust** [comment]
@meapistol 
Bitmain has over 40% of the bitcoin hash power. I propose that asic resistance is the more distributed pow and less prone to the '51%' attack. **Egalitarian mining is clearly a requirement for distributed blockchains.** I hope Bitmain sides with Bitcoin? They hold a massive amount of BCH.

**Comment by joachimneumann** [comment]
lets remove BCH

**Comment by xmijo** [comment]
> They can always fork Bisq... or use an older version. It is FOSS after all.
> 
> But we certainly have no obligation to support it or take associated risks!

imagine if they fork and start a campaign marketing it as the real bisq 🤣

**Comment by ManfredKarrer** [comment]
>> imagine if they fork and start a campaign marketing it as the real bisq 🤣

Haha, would be fun indeed and best PR for Bisq.

**Comment by meapistol** [comment]
BisqCash, BisqABC, LiteBisq, Bisq XT, ... .

**Comment by FingerCramp** [comment]
Agreed!  Cut the connection ASAP.

**Comment by aejontargaryen** [comment]
I must say it is bold to remove a top 5 cap currency. I can appreciate the motivation to refine what works  -- at defined levels of effort required.  No doubt its hard to support a currency that is being billed as decentralized but being operated as a few individual's own personal and private corporation- instead of a network. Thats not bitcoin  or any vision of Satoshi's.

On the topic of Bisq, I think it could be wise to suspend or deactivate BCH trading until the smoke clears from the hash war - at the very least.
`if (juice >= squeeze) { 
return true;
 }
else { 
return false;
}`

**Comment by ManfredKarrer** [comment]
I don't watch mainstream media. No TV, no radio. I am a poor guy cannot affort it (to waste my time on that).

**Comment by ManfredKarrer** [comment]
I think we can consider that proposal as accepted. 44 upvotes, 0 downvotes on 8.12.2018 18:15 CET.
I made a PR (https://github.com/bisq-network/bisq/pull/2096) for removing it.

**Comment by aejontargaryen** [comment]
@ManfredKarrer  What is currently the best metric for currency rankings right now in your opinion?

**Comment by rex4539** [comment]
As a "decentralized Bitcoin exchange" It is not a good idea to take sides. That is a general note, not just related to BCH.

I understand that the majority of maintainers and contributors are BTC maximalists but this is not what a decentralized exchange is all about.

**Comment by aejontargaryen** [comment]
True, meritocratic & decentralized are not to be confused.  A balance between the two, even more so.
Boom and bust cycles will bring changes upon every aspect of crypto.  Choosing sides can pigeon hole any group. That can be fine if that is the intent. If not, caution may be applicable.

**Comment by ManfredKarrer** [comment]
We have no automatic, effortless and riskless system where all the 1000s altcoins which might exist (not counting all the counterparty and ERC20 shitcoins) are listed. 

With the BSV fork and the 51% attack BCH adds effort again. If there is real risk that BSV take over and BCH becomes irrelevant we would need to send out messages, alerts new popups.... 

I am not interested to add effort to a coin which has created a lot of damage to Bitcoin. I am interested in crypto because of Bitcoin (and coins which are built with similar mindset like Monero) but I am definitely not interested to spend my time and efforts on pure speculative and fraudulent assets like BCH, BSV, Onecoin or the like. 

And those who think that all shitcoins should be listed can easily fork Bisq and run it by their own.

**Comment by aejontargaryen** [comment]
I dig it. Looks like literally everyone does.
I was just asking if there was a specific ranking metric that you used. I know some people started using coingecko's rating system for a while that included developer activity among other things to factor a score.

**Comment by aejontargaryen** [comment]
Honestly I'm glad to see any emotion. Computer science can be dangerous in that regard.

**Comment by aejontargaryen** [comment]
https://bisq.community/t/proposal-for-removing-bch/6733

**Comment by darkbluelight** [comment]
I'm pretty sure you don't care about my opinion, but I'm disappointed about this decision and your understanding of the things that led to Aug.1, 2017 and the things that happened since Aug. 1, 2017.

Bitcoin is trustless P2P electronic cash - per definition. How many of you were using it in Dec. 17 as cash? close to no one. There's a reason for that. You hope that there will be another Dec. 17, just to realize then, that none of the problems have been solved. BTC does not and will not work as trustless cash at scale. The necessary changes it would need are not going to ever be implemented. The single best candidate that does work as trustless cash at scale - you just got rid of it.

Time will show, good luck anyway.

**Comment by ManfredKarrer** [comment]
@darkbluelight 
Have you heard of the "vaporware" Lightning network? That is the solution for scaling, not blocksize increase which would make Bitcoin centralized if only big companies can affort to run full nodes. 

Too much discussed and talked about that already. Those who still don't get it will never get it. I pesonally spent so much time on that, and sorry, that this is my conclusion.  And more, those who have been in favor for BCH one year ago and have not learned anything in that year are really a lost case for me. 

Sorry to be so straight, but they not only wasted a lot of their time and money (I would not care about that part) but also created a lot of damage for the whole ecosystem and financial damage with the current price crash to many of us. If they created that by malignity like the main actors (Bitmain, Ver, Faketoshi) or by foolishness does not make so much difference in the results. 

How much more BS they need to produce to make the last BCasher understand that the world is not flat? How decentralized is it if one dev adds checkpointing on his own without any discussion or community input? How much more BS need to be produced by the most arrogant idiot in cypto space (Faketoshi)? How much more Bitmain need to prove that they control mining of BCH?

**Comment by meapistol** [comment]
@darkbluelight 
You are in a good position then. BCH is at all time low and you will make a killing by mortgaging your house and accumulating BCH. You can also fork Bisq, increase the limits and trade BCH every day and twice on Sundays.

**Comment by ManfredKarrer** [comment]
@darkbluelight
@meapistol is true and as Nassim Nicholas Taleb said in crypto you don't need to win arguments. You win or lose money by investing in what you beliefe. Just put your bet on what you beliefe. Future will tell you if you have been right or wrong.

**Comment by HostFat** [comment]
So you removed BCH because BSV trolls has sueing Kraken.

There are two possibilities, you are stupid, or you are just a big liar no less than fakesatoshi.

**Comment by ManfredKarrer** [comment]
@HostFat Sorry to hear that from a "friend". Anyways the world is big enough for people who have nothing to say to each other anymore.

**Comment by HostFat** [comment]
You have make your choices, useless and unbacked, and you lied to yourself and to the others to feel comfortable on doing them.

I understand how wrong you were when you said face to face to me that there wasn't any censorship on r/bitcoin: "**because when you got up on the morning you didn't see anything wrong.**"

Maybe you were lying from the first time.

**Comment by ftrader** [comment]
> If you support that proposal please add a thumbs up, otherwise a thumbs down. If we get a > 50% thumbs up voting we will remove BCH in the next release (the Faketoshi scamcoin we never added anyway).

BCH has nothing to do with Faketoshi. He "split".

**Comment by initCCG** [comment]
@HostFat Seems that the DAO will allow you to get BCH back in, IF you can get enough support. No?
Besides, is it not possible for you to fork a version of Bisq compatible with Bisq Main, and retain all your favorite shitcoins in it? Maybe the market will choose that.

**Comment by fyookball** [comment]
>The cost they create are externalized to the whole crypto community by creating terribly bad reputation, confusion, price crashes and now law suites. Enough is enough.

The hash war, law suits and other things and from people who are ATTACKING Bitcoin Cash.  So either you're unaware of what's going on, or you're choosing to lump us all together for some reason.

All Bitcoin Cash ever wanted, and why it is exists, is to continue Bitcoin with on-chain scaling, as a peer-to-peer electronic cash system.

**Comment by ManfredKarrer** [comment]
@fyookball No I am aware but for me it's the same crap. 2 months ago those who fight now have been together and the price crash is caused by both as well BCH has created a lot of damage to BTC even before it started as own shitcoin. Roger Ver is tricking newcomers into BCH by abusing the Bitcoin brand.... Too much that I am willing to spend time to list it here.... Those who don't get it still will never get it. Sorry to say that but true.

**Comment by fyookball** [comment]
@ManfredKarrer Well, best of the luck to the project.  People like Roger and myself never agreed with the direction of Bitcoin Core.  We see *that* as the abuse.  But as you say "Those who don't get it still will never get it."  :)

**Comment by ocZio** [comment]
Good bye fyookball, continue forking.

**Comment by ManfredKarrer** [comment]
Good luck as well fyookball. We should try to calm down all. We might be good friends if we would meet in person even if we don't share the same ideas. Communication over internet tends to get too unfriendly easily. I am sorry also that I used so strong words, just got pretty pissed because BCH/BSV created lots of damage over time to me personally (wasted dev efforts, lost money due price crash, lost time in pointless discussions,...). So lets close that proposal and stop adding more fuel in not productive discussions/fights.

**Comment by memalley** [comment]
Wow, pretty ridiculous. Don't you guys know BCH is not rid of the bad actors eg Calvin and the SV camp? The negativity you mention has left and gone to its own chain. Please don't conflate BSV with Bitcoin Cash. Of course you are free to update your work however you see fit but you show a huge blind spot in the OP thinking "BCH caused bear market". That is intellectually lazy and insincere. BTC, ETH, XRP and other highly over-valued chains have plenty of their own problems and were not caused by BCH or any other chain. How can you say at the same time 1. "BCH is a shitcoin lol, muh Roger iz scam" and 2. BCH caused bear market. That is ludicrous. What about the actual thousands of shitcoins, why ignore them? Why ignore the fact that BTC empirically failed to scale and meet network demand? This is butthurt-ism and projection on BCH, the most under-valued chain in the space, it's pretty sad to see. Your choice, your loss.

**Comment by ocZio** [comment]
> Don't you guys know BCH got rid of the bad actors eg Calvin and the SV camp? 

Stop spreading propaganda here, this is not the place.

**Comment by aejontargaryen** [comment]
@ocZio How is that propaganda?

**Comment by darkbluelight** [comment]
> @darkbluelight
> Have you heard of the "vaporware" Lightning network? That is the solution for scaling, not blocksize increase which would make Bitcoin centralized if only big companies can affort to run full nodes.
> 
> Too much discussed and talked about that already. Those who still don't get it will never get it. I pesonally spent so much time on that, and sorry, that this is my conclusion. And more, those who have been in favor for BCH one year ago and have not learned anything in that year are really a lost case for me.
> 
> Sorry to be so straight, but they not only wasted a lot of their time and money (I would not care about that part) but also created a lot of damage for the whole ecosystem and financial damage with the current price crash to many of us. If they created that by malignity like the main actors (Bitmain, Ver, Faketoshi) or by foolishness does not make so much difference in the results.
> 
> How much more BS they need to produce to make the last BCasher understand that the world is not flat? How decentralized is it if one dev adds checkpointing on his own without any discussion or community input? How much more BS need to be produced by the most arrogant idiot in cypto space (Faketoshi)? How much more Bitmain need to prove that they control mining of BCH?

@ManfredKarrer I appreciate that you took the time to give me an answer. I think we both agree that we don't agree. I really hope and wish that in some far future we have you back in the Bitcoin Cash community.

If you happen to see this post although the proposal is closed:
I'm so convinced about the good that BCH can bring to humanity that I'm willing to put my money by the mouth.
If you were to change your opinion about removing BCH and instead treating it on a same level as BTC in Bisq, I pledge to cover all your additional development and maintaining costs that incur to you or your team because of it for up to 1000 USD per month for the next 12 month, starting today. Payment preferably to a BCH address or if it has to be to a BTC address. All I would need from you is your word.

**Comment by rikur** [comment]
@darkbluelight just fork away.

**Comment by christroutner** [comment]
I anyone aware of a fork of Bisq? One that supports Bitcoin Cash? It looks like cool software, but if it doesn't use BCH, then I don't have any reason to use it. I get paid in BCH, and converting BCH to BTC just to use Bisq defeats the purpose of using it in the first place.

**Comment by vuego** [comment]
@chrisroutner I agree. It's really strange to propose removal of BCH, the transaction friendly fork of bitcoin, but keep BTC which is forcing more and more transactions off chain. Seems like an irrational emotional response. 
There's a fork of Bisq called CashX under development https://github.com/emilews/CashX/tree/no-dao

**Comment by rikur** [comment]
@vuego good riddance and please stay forked away :)

It's ironic how you scoff at layer two solutions (and btw using them is optional, not forced) when your bcash overlords force a hard-fork down their users throat at every release. If you don't understand what this means in practice.. well.. I wish you all the luck.

**Comment by vuego** [comment]
Thanks for wishing me luck. Unfortunately your post isn't helpful at all. Chris' question was about a fork. 
BTC transactions below the transaction fee is indeed forced to go off chain (I'd argue that even transactions below 3x the transaction fee is forced off chain since the recipient also have to pay a fee). Can Bisq users trade using layer 2 technology today?
There's no overlords that can force hard forks. Miners need to actively accept the fork by upgrading their software. If they don't, there will be a split and anyone is free to follow any chain fork.

**Comment by rikur** [comment]
Yeah, good luck.
